"""Strict, application-owned contracts for one local PDF session."""

from enum import StrEnum
from typing import Annotated, Literal
from uuid import UUID

from pydantic import Field, model_validator

from app.ai.schemas import ContractModel


class PdfExtractionMethod(StrEnum):
    """How a page was read; it is never model-supplied metadata."""

    NATIVE = "native"
    VISUAL = "visual"
    MIXED = "mixed"


class PdfSource(ContractModel):
    """Safe metadata for one uploaded source PDF, without a filesystem path."""

    upload_id: UUID
    source_id: UUID
    file_name: str = Field(min_length=1, max_length=255)
    sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    mime_type: Literal["application/pdf"] = "application/pdf"
    page_count: int = Field(ge=1, le=200)


class PdfTextBlock(ContractModel):
    """An immutable, positioned native-text block generated by WorkBench."""

    block_id: str = Field(pattern=r"^pdfb_[0-9a-f]{64}$")
    page_number: int = Field(ge=1)
    text: str = Field(min_length=1, max_length=20_000)
    x0: float = Field(ge=0)
    y0: float = Field(ge=0)
    x1: float = Field(gt=0)
    y1: float = Field(gt=0)
    font_name: str | None = Field(default=None, max_length=200)
    font_size: float | None = Field(default=None, gt=0, le=200)

    @model_validator(mode="after")
    def require_nonempty_rectangle(self) -> PdfTextBlock:
        if self.x1 <= self.x0 or self.y1 <= self.y0:
            raise ValueError("PDF block rectangle must have positive area")
        return self


class PdfTable(ContractModel):
    """Bounded table text retained with a real source page."""

    page_number: int = Field(ge=1)
    rows: tuple[tuple[str, ...], ...] = Field(min_length=1, max_length=100)


class PdfPage(ContractModel):
    """One inspected page and its application-controlled evidence."""

    page_number: int = Field(ge=1)
    extraction_method: PdfExtractionMethod
    text_blocks: tuple[PdfTextBlock, ...] = ()
    tables: tuple[PdfTable, ...] = ()
    visual_text: str = Field(default="", max_length=30_000)
    uncertain: bool = False
    uncertainty_reason: str | None = Field(default=None, max_length=500)

    @model_validator(mode="after")
    def require_uncertainty_reason(self) -> PdfPage:
        if self.uncertain and not self.uncertainty_reason:
            raise ValueError("uncertain PDF pages require an uncertainty reason")
        if not self.uncertain and self.uncertainty_reason is not None:
            raise ValueError("certain PDF pages cannot include an uncertainty reason")
        return self


class PdfDocumentDraft(ContractModel):
    """Structured content that can be rendered only after approval."""

    title: str = Field(min_length=1, max_length=200)
    purpose: str = Field(min_length=1, max_length=1_000)
    sections: tuple[PdfDraftSection, ...] = Field(min_length=1, max_length=30)
    header: str | None = Field(default=None, max_length=200)
    footer: str | None = Field(default=None, max_length=200)
    uncertainty_statement: str | None = Field(default=None, max_length=1_000)


class PdfDraftSection(ContractModel):
    page_break_before: bool = False
    heading: str = Field(min_length=1, max_length=200)
    paragraphs: tuple[str, ...] = Field(min_length=1, max_length=100)
    bullets: tuple[str, ...] = Field(default=(), max_length=100)
    table: tuple[tuple[str, ...], ...] = Field(default=(), max_length=100)


class PdfReplaceText(ContractModel):
    operation: Literal["replaceText"] = "replaceText"
    block_id: str = Field(pattern=r"^pdfb_[0-9a-f]{64}$")
    replacement: str = Field(min_length=1, max_length=2_000)


class PdfRedactBlock(ContractModel):
    operation: Literal["redactBlock"] = "redactBlock"
    block_id: str = Field(pattern=r"^pdfb_[0-9a-f]{64}$")


class PdfAddAnnotation(ContractModel):
    operation: Literal["addAnnotation"] = "addAnnotation"
    page_number: int = Field(ge=1)
    text: str = Field(min_length=1, max_length=2_000)
    x: float = Field(ge=0)
    y: float = Field(ge=0)


class PdfOverlay(ContractModel):
    operation: Literal["overlayText"] = "overlayText"
    page_number: int = Field(ge=1)
    x0: float = Field(ge=0)
    y0: float = Field(ge=0)
    x1: float = Field(gt=0)
    y1: float = Field(gt=0)
    text: str = Field(min_length=1, max_length=2_000)
    font_size: float = Field(default=10, ge=6, le=36)


class PdfRedactRegion(ContractModel):
    operation: Literal["redactRegion"] = "redactRegion"
    page_number: int = Field(ge=1)
    x0: float = Field(ge=0)
    y0: float = Field(ge=0)
    x1: float = Field(gt=0)
    y1: float = Field(gt=0)


class PdfPageSequence(ContractModel):
    """Select source pages in order; omission deletes and repetition duplicates."""

    operation: Literal["selectPages"] = "selectPages"
    pages: tuple[int, ...] = Field(min_length=1, max_length=200)


class PdfAddPages(ContractModel):
    operation: Literal["addPages"] = "addPages"
    position: Literal["before", "after"]
    draft: PdfDocumentDraft


PdfEditOperation = Annotated[
    PdfReplaceText
    | PdfRedactBlock
    | PdfAddAnnotation
    | PdfOverlay
    | PdfRedactRegion
    | PdfPageSequence
    | PdfAddPages,
    Field(discriminator="operation"),
]


class PdfEditPlan(ContractModel):
    """A bounded proposed edit; caller validates IDs against inspected layout."""

    source_id: UUID
    output_file_name: str = Field(min_length=5, max_length=255, pattern=r"^[^/\\]+\.pdf$")
    operations: tuple[PdfEditOperation, ...] = Field(min_length=1, max_length=50)

    @model_validator(mode="after")
    def separate_page_operations(self) -> PdfEditPlan:
        if len(self.operations) > 1 and any(
            isinstance(op, (PdfPageSequence, PdfAddPages)) for op in self.operations
        ):
            raise ValueError("Page reordering/addition must be a separate approved edit")
        return self


class PdfArtifact(ContractModel):
    """Validated local output facts; path is intentionally absent."""

    artifact_id: UUID
    file_name: str = Field(min_length=5, max_length=255, pattern=r"^[^/\\]+\.pdf$")
    sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    size_bytes: int = Field(ge=1)
    page_count: int = Field(ge=1)
    validated: Literal[True] = True


class PdfTurnIntent(ContractModel):
    tool: Literal["summarize_pdf", "answer_pdf", "create_pdf", "edit_pdf"]


class PdfClaim(ContractModel):
    text: str = Field(min_length=1, max_length=4_000)
    pages: tuple[int, ...] = Field(min_length=1, max_length=200)


class GroundedPdfAnswer(ContractModel):
    claims: tuple[PdfClaim, ...] = Field(default=(), max_length=100)
    uncertainties: tuple[str, ...] = Field(default=(), max_length=30)
    missing_information: str | None = Field(default=None, max_length=2_000)

    @model_validator(mode="after")
    def require_content(self) -> GroundedPdfAnswer:
        if not self.claims and not self.missing_information:
            raise ValueError("answer must contain evidence or explain missing information")
        return self


class PdfTurnRequest(ContractModel):
    message: str = Field(min_length=1, max_length=10_000)
    client_request_id: UUID
    upload_id: UUID | None = None


class PdfApproval(ContractModel):
    approval_id: UUID
    tool: Literal["create_pdf", "edit_pdf"]
    arguments_hash: str
    status: Literal["pending", "executing", "rejected", "completed", "failed"] = "pending"
    file_name: str
    draft: PdfDocumentDraft | None = None
    edit: PdfEditPlan | None = None


class PdfApprovalDecision(ContractModel):
    approve: bool
    arguments_hash: str = Field(pattern=r"^[0-9a-f]{64}$")


class PdfTurnResult(ContractModel):
    request_id: UUID
    user_message: str
    answer: str
    tool: Literal["summarize_pdf", "answer_pdf", "create_pdf", "edit_pdf"]
    pages: tuple[int, ...] = ()
    selected_model: str
    used_fallback: bool = False
    approval: PdfApproval | None = None
    artifact: PdfArtifact | None = None


class PdfSessionView(ContractModel):
    source: PdfSource | None = None
    pages: tuple[PdfPage, ...] = ()
    turns: tuple[PdfTurnResult, ...] = ()
    activity: tuple[str, ...] = ()
